### ISSUE TITLE
How can I disable incoming ANY request

### ISSUE THREAD

**Issue by ookangzheng** [fardog/secureoperator#11]
<img width="669" alt="screen shot 2017-05-28 at 23 28 50" src="https://cloud.githubusercontent.com/assets/6301735/26529944/87e7638a-43fd-11e7-88c4-47c53c91e0e4.png">
How can I block or Drop the ANY Request

**Comment by fardog** [comment]
there is no support for disabling a specific type of DNS request; `secure-operator` will forward any request sent to it. if you need to control any access to `secure-operator`, it's recommended to run it behind another DNS server such as [dnsmasq](http://www.thekelleys.org.uk/dnsmasq/doc.html). it's actually just the recommended configuration in general, since `secure-operator` itself doesn't perform any sort of caching; it just forwards every request directly to Google's DNS-over-HTTPS servers.

i'm going to close this issue for now, but please let me know and re-open it if that doesn't answer your question.
